# Generated by Django 3.0.6 on 2020-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scarp_material',
            name='doc_no',
            field=models.CharField(max_length=10),
        ),
    ]
