# Generated by Django 3.0.6 on 2020-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manufacturing', '0003_auto_20200529_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scarp_material',
            old_name='planner_reason',
            new_name='qa_classification',
        ),
        migrations.RenameField(
            model_name='scarp_material',
            old_name='qa_reason',
            new_name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='scarp_material',
            name='store1_reason',
        ),
        migrations.RemoveField(
            model_name='scarp_material',
            name='store2_reason',
        ),
        migrations.AddField(
            model_name='scarp_material',
            name='rejection_department',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scarp_material',
            name='rejection_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
